// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lwpls_predict_cpp
arma::cube lwpls_predict_cpp(const arma::mat& x, const arma::mat& y, const arma::mat& new_x, const int num_comp, const double localization, const int neighbors, const double tol);
RcppExport SEXP _lwpls_lwpls_predict_cpp(SEXP xSEXP, SEXP ySEXP, SEXP new_xSEXP, SEXP num_compSEXP, SEXP localizationSEXP, SEXP neighborsSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type new_x(new_xSEXP);
    Rcpp::traits::input_parameter< const int >::type num_comp(num_compSEXP);
    Rcpp::traits::input_parameter< const double >::type localization(localizationSEXP);
    Rcpp::traits::input_parameter< const int >::type neighbors(neighborsSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(lwpls_predict_cpp(x, y, new_x, num_comp, localization, neighbors, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lwpls_lwpls_predict_cpp", (DL_FUNC) &_lwpls_lwpls_predict_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_lwpls(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
