#' @title Wrapper For RNIRS LWPLSR And LWPLSDA Functions
#'
#' @description Based on arguments, this wrapper routes the data and arguments to the two `lwpls` functions that are regression/classification.
#'
#' @param x A data frame or matrix of predictors.
#' @param y For classification, a factor. For regression, a matrix, vector, or data frame.
#' @param num_comp The number of LWPLS components. If left NULL, the maximum possible is used.
#' @param neighbors The number of neighbors considered at each prediction. If left NULL, `seq(1,5)` is used.
#' @param shapefactor Scaling shape factor of the function of the weights applied to the neighbors in the weighted PLSR. If left NULL, `seq(1,10)` is used.
#'
#' @return A model object generated by [rnirs::lwplsr()], [rnirs::lwplsda()]
#' @export lwplsFit
#' @keywords internal
#'
#'
lwplsFit <- function(x, y,  num_comp = NULL, neighbors = NULL, shapefactor = NULL) {
  p <- ncol(x)

  if (!is.matrix(x)) {
    x <- as.matrix(x)
  }

  if (is.null(num_comp)) {
    num_comp <- p
  } else {
    num_comp <- min(num_comp, p)
  }

  if (is.null(shapefactor)) {
    shapefactor <- seq(1, 10)
  }

  if (is.null(neighbors)) {
    shapefactor <- seq(1, 5)
  }

  if (is.numeric(y)) {
    res <- rnirs::lwplsr(
      Xr = x,
      Yr = y,
      Xu = x,
      Yu = NULL,
      ncompdis = NULL,
      diss = "euclidean",
      h = shapefactor,
      k = neighbors,
      ncomp = num_comp,
      cri = 5,
      stor = TRUE,
      print = FALSE
      )
  } else {
    res <- rnirs::lwplsda(
      Xr = x,
      Yr = y,
      Xu = x,
      Yu = NULL,
      ncompdis = NULL,
      diss = "euclidean",
      h = shapefactor,
      k = neighbors,
      ncomp = num_comp,
      cri = 3,
      stor = TRUE,
      print = FALSE
    )
  }
  res
}
