# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lwpls_predict_cpp <- function(x, y, new_x, num_comp, localization, neighbors, tol) {
    .Call(`_lwpls_lwpls_predict_cpp`, x, y, new_x, num_comp, localization, neighbors, tol)
}

