# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lwpls_predict_cpp <- function(x, y, new_x, dist_x, dist_new, num_comp, localization, neighbors, tol) {
    .Call(`_lwpls_lwpls_predict_cpp`, x, y, new_x, dist_x, dist_new, num_comp, localization, neighbors, tol)
}

lwpls_general_cpp <- function(x, y, new_x, dist_x, dist_new, comps, localization, neighbors, sparsity, robust, fair_c, hampel_probs, max_iter, classification, tol) {
    .Call(`_lwpls_lwpls_general_cpp`, x, y, new_x, dist_x, dist_new, comps, localization, neighbors, sparsity, robust, fair_c, hampel_probs, max_iter, classification, tol)
}

lwpls_local_cpp <- function(x, y, new_x, dist_x, dist_new, num_comp, localization, neighbors, sparsity, robust, fair_c, hampel_probs, max_iter, classification, tol, level) {
    .Call(`_lwpls_lwpls_local_cpp`, x, y, new_x, dist_x, dist_new, num_comp, localization, neighbors, sparsity, robust, fair_c, hampel_probs, max_iter, classification, tol, level)
}

